schema_version: 1
setup_command: python3 -m venv .venv
install_command: .venv/bin/pip install -e '.[dev]'
test_command: .venv/bin/pytest
timeout_seconds: 600
max_files_changed: 30
max_diff_loc: 1500

security:
  enabled: true
  fail_severity: high
  secret_scanner: gitleaks
  sensitive_paths:
    - ".github/workflows/**"
    - "infra/**"

release_governor:
  enabled: true
  verification_workflow_name: "Verify main"
  deploy_workflow_name: deploy.yml

memory:
  enabled: true
  retention_days: 90
  max_matches: 3
  comment_on_pr: true
  comment_on_incident_issue: true
