"""GitHub issue comment creation for failure notifications."""

from urllib.parse import urlparse

from github import Auth, Github, GithubException

from booty.logging import get_logger

logger = get_logger()


def _get_repo(github_token: str, repo_url: str):
    """Get GitHub repository object.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL (e.g., https://github.com/owner/repo or https://github.com/owner/repo.git)

    Returns:
        PyGithub Repository object
    """
    # Parse owner/repo from URL
    parsed = urlparse(repo_url)
    path = parsed.path

    # Remove leading slash and trailing .git if present
    if path.startswith("/"):
        path = path[1:]
    if path.endswith(".git"):
        path = path[:-4]

    owner_repo = path

    # Authenticate with GitHub
    auth = Auth.Token(github_token)
    g = Github(auth=auth)

    # Get repository
    return g.get_repo(owner_repo)


def post_failure_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
    error_message: str,
    attempts: int,
    max_retries: int,
) -> None:
    """Post a failure comment on a GitHub issue.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number
        error_message: Error details from failed test run
        attempts: Number of attempts made
        max_retries: Maximum retry limit

    Raises:
        GithubException: If comment creation fails
    """
    try:
        # Get repository and issue
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        # Format comment body
        body = f"""## Booty Build Failed

After {attempts}/{max_retries} attempt(s), the generated code did not pass tests.

### Error Details

```
{error_message}
```

A draft PR has been opened with the latest attempt for manual review.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""

        # Create comment
        issue.create_comment(body)
        logger.info("failure_comment_posted", issue_number=issue_number)

    except GithubException as e:
        logger.error(
            "failure_comment_post_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise
