"""GitHub issue comment creation for failure notifications."""

from urllib.parse import urlparse

from github import Auth, Github, GithubException

from booty.logging import get_logger

logger = get_logger()


def _get_repo(github_token: str, repo_url: str):
    """Get GitHub repository object.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL (e.g., https://github.com/owner/repo or https://github.com/owner/repo.git)

    Returns:
        PyGithub Repository object
    """
    # Parse owner/repo from URL
    parsed = urlparse(repo_url)
    path = parsed.path

    # Remove leading slash and trailing .git if present
    if path.startswith("/"):
        path = path[1:]
    if path.endswith(".git"):
        path = path[:-4]

    owner_repo = path

    # Authenticate with GitHub
    auth = Auth.Token(github_token)
    g = Github(auth=auth)

    # Get repository
    return g.get_repo(owner_repo)


def post_failure_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
    error_message: str,
) -> None:
    """Post a failure comment on a GitHub issue.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number
        error_message: Error details from failed test run

    Raises:
        GithubException: If comment creation fails
    """
    try:
        # Get repository and issue
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        # Format comment body
        body = f"""## Booty Build Failed

{error_message}

A draft PR has been opened with the latest attempt for manual review.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""

        # Create comment
        issue.create_comment(body)
        logger.info("failure_comment_posted", issue_number=issue_number)

    except GithubException as e:
        logger.error(
            "failure_comment_post_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_promotion_failure_comment(
    github_token: str,
    repo_url: str,
    pr_number: int,
    reason: str,
    attempts: int = 3,
) -> None:
    """Post a neutral comment when PR promotion to ready-for-review failed.

    If posting the comment fails (permissions, API error), logs only and does
    not re-raise (per CONTEXT: fall back to logs only, no UI change).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        reason: Brief reason for failure (e.g., API error message)
        attempts: Number of promotion attempts made (default 3)
    """
    try:
        repo = _get_repo(github_token, repo_url)
        pr = repo.get_pull(pr_number)
        body = f"""## Could not promote to ready for review

Promotion was not completed after {attempts} attempt(s).

{reason}

---
PR remains in draft for manual review."""
        pr.as_issue().create_comment(body)
        logger.info("promotion_failure_comment_posted", pr_number=pr_number)
    except GithubException as e:
        logger.error(
            "promotion_failure_comment_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )


def post_verifier_failure_comment(
    github_token: str,
    repo_url: str,
    pr_number: int,
    summary: str,
    truncated_output: str,
) -> None:
    """Post or update Verifier failure comment on a PR.

    Finds existing comment with '## Verifier Results' and edits it; otherwise creates new.
    Keeps a single Verifier results comment per PR (edit/replace, not append).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        summary: Summary of failure
        truncated_output: Truncated stderr (e.g. last ~50 lines)
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(pr_number)
        body = f"""## Verifier Results

{summary}

```
{truncated_output}
```

---
*Generated by [Booty Verifier](https://github.com/datashaman/booty)*"""

        for comment in issue.get_comments():
            if "## Verifier Results" in (comment.body or ""):
                comment.edit(body)
                logger.info("verifier_failure_comment_updated", pr_number=pr_number)
                return

        issue.create_comment(body)
        logger.info("verifier_failure_comment_posted", pr_number=pr_number)
    except GithubException as e:
        logger.error(
            "verifier_failure_comment_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_self_modification_disabled_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
) -> None:
    """Post a comment explaining self-modification is disabled.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number

    Raises:
        GithubException: If comment creation fails
    """
    try:
        # Get repository and issue
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        # Format comment body
        body = """## Self-modification disabled

This issue was labeled for processing, but self-modification is not enabled for this Booty instance.

Set BOOTY_SELF_MODIFY_ENABLED=true to allow Booty to process issues against its own repository.

Self-modification requires explicit opt-in and will always create draft PRs requiring human review.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""

        # Create comment
        issue.create_comment(body)
        logger.info("self_modification_disabled_comment_posted", issue_number=issue_number)

    except GithubException as e:
        logger.error(
            "self_modification_disabled_comment_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise
