"""GitHub issue comment creation for failure notifications."""

import re
from urllib.parse import urlparse

from github import Auth, Github, GithubException

from booty.logging import get_logger

logger = get_logger()


def _get_repo(github_token: str, repo_url: str):
    """Get GitHub repository object.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL (e.g., https://github.com/owner/repo or https://github.com/owner/repo.git)

    Returns:
        PyGithub Repository object
    """
    # Parse owner/repo from URL
    parsed = urlparse(repo_url)
    path = parsed.path

    # Remove leading slash and trailing .git if present
    if path.startswith("/"):
        path = path[1:]
    if path.endswith(".git"):
        path = path[:-4]

    owner_repo = path

    # Authenticate with GitHub
    auth = Auth.Token(github_token)
    g = Github(auth=auth)

    # Get repository
    return g.get_repo(owner_repo)


def post_failure_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
    error_message: str,
) -> None:
    """Post a failure comment on a GitHub issue.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number
        error_message: Error details from failed test run

    Raises:
        GithubException: If comment creation fails
    """
    try:
        # Get repository and issue
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        # Format comment body
        body = f"""## Booty Build Failed

{error_message}

A draft PR has been opened with the latest attempt for manual review.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""

        # Create comment
        issue.create_comment(body)
        logger.info("failure_comment_posted", issue_number=issue_number)

    except GithubException as e:
        logger.error(
            "failure_comment_post_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_promotion_failure_comment(
    github_token: str,
    repo_url: str,
    pr_number: int,
    reason: str,
    attempts: int = 3,
) -> None:
    """Post a neutral comment when PR promotion to ready-for-review failed.

    If posting the comment fails (permissions, API error), logs only and does
    not re-raise (per CONTEXT: fall back to logs only, no UI change).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        reason: Brief reason for failure (e.g., API error message)
        attempts: Number of promotion attempts made (default 3)
    """
    try:
        repo = _get_repo(github_token, repo_url)
        pr = repo.get_pull(pr_number)
        body = f"""## Could not promote to ready for review

Promotion was not completed after {attempts} attempt(s).

{reason}

---
PR remains in draft for manual review."""
        pr.as_issue().create_comment(body)
        logger.info("promotion_failure_comment_posted", pr_number=pr_number)
    except GithubException as e:
        logger.error(
            "promotion_failure_comment_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )


def post_verifier_failure_comment(
    github_token: str,
    repo_url: str,
    pr_number: int,
    summary: str,
    truncated_output: str,
) -> None:
    """Post or update Verifier failure comment on a PR.

    Finds existing comment with '## Verifier Results' and edits it; otherwise creates new.
    Keeps a single Verifier results comment per PR (edit/replace, not append).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        summary: Summary of failure
        truncated_output: Truncated stderr (e.g. last ~50 lines)
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(pr_number)
        body = f"""## Verifier Results

{summary}

```
{truncated_output}
```

---
*Generated by [Booty Verifier](https://github.com/datashaman/booty)*"""

        for comment in issue.get_comments():
            if "## Verifier Results" in (comment.body or ""):
                comment.edit(body)
                logger.info("verifier_failure_comment_updated", pr_number=pr_number)
                return

        issue.create_comment(body)
        logger.info("verifier_failure_comment_posted", pr_number=pr_number)
    except GithubException as e:
        logger.error(
            "verifier_failure_comment_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_memory_comment(
    github_token: str,
    repo_url: str,
    pr_number: int,
    body: str,
) -> None:
    """Post or update Memory comment on a PR.

    Finds existing comment with '<!-- booty-memory -->' and edits it;
    otherwise creates new. Keeps a single Memory comment per PR.
    Caller is responsible for not calling when body would be empty (zero matches).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        body: Comment body (must include marker; caller provides formatted content)
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(pr_number)
        full_body = f"""## Memory: related history

{body}

<!-- booty-memory -->"""

        for comment in issue.get_comments():
            if "<!-- booty-memory -->" in (comment.body or ""):
                comment.edit(full_body)
                logger.info("memory_comment_updated", pr_number=pr_number)
                return

        issue.create_comment(full_body)
        logger.info("memory_comment_posted", pr_number=pr_number)
    except GithubException as e:
        logger.error(
            "memory_comment_post_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_plan_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
    body: str,
) -> None:
    """Post or update Plan comment on a GitHub issue.

    Finds existing comment with '<!-- booty-plan -->' and edits it;
    otherwise creates new. Keeps a single plan comment per issue.
    Body must include <!-- booty-plan --> for find-and-edit.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number
        body: Comment body (pre-formatted, must include marker)

    Raises:
        GithubException: If comment creation/update fails
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        for comment in issue.get_comments():
            if "<!-- booty-plan -->" in (comment.body or ""):
                comment.edit(body)
                logger.info("plan_comment_updated", issue_number=issue_number)
                return

        issue.create_comment(body)
        logger.info("plan_comment_posted", issue_number=issue_number)
    except GithubException as e:
        logger.error(
            "plan_comment_post_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_builder_blocked_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
) -> None:
    """Post a comment when Builder is blocked due to missing plan.

    Planner-first architecture: Builder only runs when a valid plan exists.
    No fallback to raw issue interpretation.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number

    Raises:
        GithubException: If comment creation fails
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)
        body = """## Builder blocked — no plan found

Add `agent` to generate a plan first, or ensure a plan exists for this issue.

Builder is a pure executor: it only runs against structured Plan artifacts produced by the Planner.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""
        issue.create_comment(body)
        logger.info("builder_blocked_comment_posted", issue_number=issue_number)
    except GithubException as e:
        logger.error(
            "builder_blocked_comment_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_architect_invalid_config_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
) -> None:
    """Post a comment when Architect config is invalid (unknown keys in .booty.yml)."""
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)
        body = """Architect review required — invalid architect config in .booty.yml

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""
        issue.create_comment(body)
        logger.info("architect_invalid_config_comment_posted", issue_number=issue_number)
    except GithubException as e:
        logger.error(
            "architect_invalid_config_comment_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def update_plan_comment_with_architect_section(
    github_token: str,
    repo_url: str,
    issue_number: int,
    architect_section: str,
) -> bool:
    """Update plan comment with booty-architect section.

    Finds comment containing '<!-- booty-plan -->', injects architect_section before <details>.
    If <!-- booty-architect --> already exists, replaces that block; else inserts before <details>.
    If no plan comment found: log warning and return (Planner should have posted).

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number
        architect_section: Pre-formatted <!-- booty-architect --> block
    """
    try:
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        for comment in issue.get_comments():
            body = comment.body or ""
            if "<!-- booty-plan -->" not in body:
                continue

            # Replace existing booty-architect block or insert before <details>
            booty_architect_pattern = re.compile(
                r"<!-- booty-architect -->.*?<!-- /booty-architect -->",
                re.DOTALL,
            )
            if booty_architect_pattern.search(body):
                new_body = booty_architect_pattern.sub(architect_section, body, count=1)
            else:
                # Insert before <details> or before <!-- booty-plan --> if no details
                if "<details>" in body:
                    idx = body.index("<details>")
                    new_body = body[:idx] + architect_section + "\n\n" + body[idx:]
                else:
                    idx = body.index("<!-- booty-plan -->")
                    new_body = body[:idx] + architect_section + "\n\n" + body[idx:]

            comment.edit(new_body)
            logger.info(
                "architect_section_updated",
                issue_number=issue_number,
            )
            return True

        logger.warning(
            "plan_comment_not_found",
            issue_number=issue_number,
            message="No plan comment to update with architect section",
        )
        return False
    except GithubException as e:
        logger.error(
            "update_plan_comment_with_architect_section_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_architect_blocked_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
    reason: str = "",
) -> None:
    """Update plan comment when Architect blocks (structurally unsafe).

    Updates the same plan comment with booty-architect Blocked section (ARCH-19).
    If no plan comment found: fall back to creating minimal comment for operator visibility.
    Keeps exact phrase "Architect review required — plan is structurally unsafe."
    """
    from booty.architect.output import format_architect_section

    architect_section = format_architect_section("blocked", reason=reason or None)
    try:
        updated = update_plan_comment_with_architect_section(
            github_token, repo_url, issue_number, architect_section
        )
        if updated:
            return

        # Fallback: no plan comment found, create minimal comment
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)
        body = "Architect review required — plan is structurally unsafe."
        if reason:
            body += f" ({reason})"
        body += "\n\n---\n*Generated by [Booty](https://github.com/datashaman/booty)*"
        issue.create_comment(body)
        logger.info("architect_blocked_comment_posted", issue_number=issue_number)
    except GithubException as e:
        logger.error(
            "architect_blocked_comment_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise


def post_self_modification_disabled_comment(
    github_token: str,
    repo_url: str,
    issue_number: int,
) -> None:
    """Post a comment explaining self-modification is disabled.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        issue_number: GitHub issue number

    Raises:
        GithubException: If comment creation fails
    """
    try:
        # Get repository and issue
        repo = _get_repo(github_token, repo_url)
        issue = repo.get_issue(issue_number)

        # Format comment body
        body = """## Self-modification disabled

This issue was labeled for processing, but self-modification is not enabled for this Booty instance.

Set BOOTY_SELF_MODIFY_ENABLED=true to allow Booty to process issues against its own repository.

Self-modification requires explicit opt-in and will always create draft PRs requiring human review.

---
*Generated by [Booty](https://github.com/datashaman/booty)*"""

        # Create comment
        issue.create_comment(body)
        logger.info("self_modification_disabled_comment_posted", issue_number=issue_number)

    except GithubException as e:
        logger.error(
            "self_modification_disabled_comment_failed",
            issue_number=issue_number,
            error=str(e),
            status=e.status,
        )
        raise
