"""Pull request creation via PyGithub."""

from urllib.parse import urlparse

from github import Auth, Github, GithubException

from booty.logging import get_logger

logger = get_logger()


def create_pull_request(
    github_token: str,
    repo_url: str,
    head_branch: str,
    base_branch: str,
    title: str,
    body: str,
    draft: bool = False,
) -> int:
    """Create a pull request on GitHub.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL (e.g., https://github.com/owner/repo or https://github.com/owner/repo.git)
        head_branch: Source branch name
        base_branch: Target branch name
        title: PR title
        body: PR body (markdown)
        draft: Whether to create as draft PR (default: False)

    Returns:
        PR number

    Raises:
        GithubException: If PR creation fails
    """
    try:
        # Parse owner/repo from URL
        parsed = urlparse(repo_url)
        path = parsed.path

        # Remove leading slash and trailing .git if present
        if path.startswith("/"):
            path = path[1:]
        if path.endswith(".git"):
            path = path[:-4]

        owner_repo = path

        # Authenticate with GitHub
        auth = Auth.Token(github_token)
        g = Github(auth=auth)

        # Get repository
        repo = g.get_repo(owner_repo)
        logger.info("repository_accessed", repo=owner_repo)

        # Create pull request
        pr = repo.create_pull(
            title=title, body=body, head=head_branch, base=base_branch, draft=draft
        )

        logger.info(
            "pull_request_created",
            pr_number=pr.number,
            url=pr.html_url,
            draft=draft,
        )
        return pr.number

    except GithubException as e:
        logger.error("pull_request_creation_failed", error=str(e), status=e.status)
        raise


def format_pr_body(
    approach: str,
    file_changes: list[dict],
    testing_notes: str,
    issue_number: int,
) -> str:
    """Format structured PR body.

    Args:
        approach: Summary of approach taken
        file_changes: List of dicts with keys: path, operation, explanation
        testing_notes: Testing instructions
        issue_number: GitHub issue number

    Returns:
        Formatted PR body markdown
    """
    # Build changes table
    table_rows = []
    for change in file_changes:
        path = change["path"]
        operation = change["operation"]
        explanation = change["explanation"]
        table_rows.append(f"| {path} | {operation} | {explanation} |")

    changes_table = "\n".join(table_rows)

    # Format body
    body = f"""## Summary
{approach}

## Changes
| File | Operation | Description |
|------|-----------|-------------|
{changes_table}

## Testing
{testing_notes}

---
Fixes #{issue_number}
Generated by [Booty](https://github.com/datashaman/booty)"""

    return body


def add_agent_builder_label(
    github_token: str,
    repo_url: str,
    pr_number: int,
    label: str = "agent:builder",
) -> None:
    """Add agent:builder (or custom) label to a PR.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number
        label: Label name (default agent:builder)

    Raises:
        GithubException: If label addition fails
    """
    try:
        parsed = urlparse(repo_url)
        path = parsed.path
        if path.startswith("/"):
            path = path[1:]
        if path.endswith(".git"):
            path = path[:-4]
        owner_repo = path

        auth = Auth.Token(github_token)
        g = Github(auth=auth)
        repo = g.get_repo(owner_repo)
        pr = repo.get_pull(pr_number)

        try:
            pr.add_to_labels(label)
            logger.info("agent_builder_label_added", pr_number=pr_number, label=label)
        except GithubException as e:
            if e.status == 404:
                logger.info("creating_agent_builder_label", label=label)
                repo.create_label(label, "0366d6", "PR created by Booty Builder agent")
                pr.add_to_labels(label)
                logger.info("agent_builder_label_created_and_added", pr_number=pr_number)
            else:
                raise
    except GithubException as e:
        logger.error(
            "agent_builder_label_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )
        raise


def add_self_modification_metadata(
    github_token: str,
    repo_url: str,
    pr_number: int,
    reviewer_username: str,
) -> None:
    """Add self-modification label and request reviewer for a PR.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL
        pr_number: PR number to add metadata to
        reviewer_username: GitHub username to request review from (empty string to skip)

    Raises:
        GithubException: If metadata addition fails
    """
    try:
        # Parse owner/repo from URL
        parsed = urlparse(repo_url)
        path = parsed.path

        if path.startswith("/"):
            path = path[1:]
        if path.endswith(".git"):
            path = path[:-4]

        owner_repo = path

        # Authenticate with GitHub
        auth = Auth.Token(github_token)
        g = Github(auth=auth)

        # Get repository and PR
        repo = g.get_repo(owner_repo)
        pr = repo.get_pull(pr_number)

        # Add self-modification label (create if doesn't exist)
        try:
            pr.add_to_labels("self-modification")
            logger.info("self_modification_label_added", pr_number=pr_number)
        except GithubException as e:
            # Label doesn't exist, create it
            if e.status == 404:
                logger.info("creating_self_modification_label")
                repo.create_label(
                    "self-modification",
                    "ff6b6b",
                    "Self-modification PR requiring manual review",
                )
                pr.add_to_labels("self-modification")
                logger.info("self_modification_label_created_and_added", pr_number=pr_number)
            else:
                raise

        # Request reviewer if provided
        if reviewer_username:
            try:
                pr.create_review_request(reviewers=[reviewer_username])
                logger.info(
                    "reviewer_requested",
                    pr_number=pr_number,
                    reviewer=reviewer_username,
                )
            except GithubException as e:
                logger.warning(
                    "reviewer_request_failed",
                    pr_number=pr_number,
                    reviewer=reviewer_username,
                    error=str(e),
                    status=e.status,
                )

    except GithubException as e:
        logger.error(
            "self_modification_metadata_failed",
            pr_number=pr_number,
            error=str(e),
            status=e.status,
        )
        raise


def format_self_modification_pr_body(
    approach: str,
    file_changes: list[dict],
    testing_notes: str,
    issue_number: int,
    protected_paths_checked: list[str],
    changed_files: list[str],
) -> str:
    """Format PR body with safety summary for self-modification PRs.

    Args:
        approach: Summary of approach taken
        file_changes: List of dicts with keys: path, operation, explanation
        testing_notes: Testing instructions
        issue_number: GitHub issue number
        protected_paths_checked: List of protected paths that were verified
        changed_files: List of all changed file paths

    Returns:
        Formatted PR body markdown with safety summary section
    """
    # Safety summary section
    file_count = len(changed_files)
    files_to_show = changed_files[:10]
    has_more = len(changed_files) > 10

    files_list = "\n".join([f"- {file}" for file in files_to_show])
    if has_more:
        files_list += f"\n- ... and {len(changed_files) - 10} more"

    protected_list = "\n".join([f"- {path}" for path in protected_paths_checked])

    safety_summary = f"""## Safety Summary

**Draft by design:** Self-modification PRs are not auto-promoted.

**File Changes:** {file_count} file(s) modified

**Changed Files:**
{files_list}

**Protected Paths Verified:**
{protected_list}

**Confirmation:** No protected paths were modified.

---

"""

    # Build changes table
    table_rows = []
    for change in file_changes:
        path = change["path"]
        operation = change["operation"]
        explanation = change["explanation"]
        table_rows.append(f"| {path} | {operation} | {explanation} |")

    changes_table = "\n".join(table_rows)

    # Format full body with safety summary at top
    body = f"""{safety_summary}## Summary
{approach}

## Changes
| File | Operation | Description |
|------|-----------|-------------|
{changes_table}

## Testing
{testing_notes}

---
Fixes #{issue_number}
Generated by Booty (self-modification)"""

    return body
