"""Pull request creation via PyGithub."""

from urllib.parse import urlparse

from github import Auth, Github, GithubException

from booty.logging import get_logger

logger = get_logger()


def create_pull_request(
    github_token: str,
    repo_url: str,
    head_branch: str,
    base_branch: str,
    title: str,
    body: str,
    draft: bool = False,
) -> int:
    """Create a pull request on GitHub.

    Args:
        github_token: GitHub authentication token
        repo_url: Repository URL (e.g., https://github.com/owner/repo or https://github.com/owner/repo.git)
        head_branch: Source branch name
        base_branch: Target branch name
        title: PR title
        body: PR body (markdown)
        draft: Whether to create as draft PR (default: False)

    Returns:
        PR number

    Raises:
        GithubException: If PR creation fails
    """
    try:
        # Parse owner/repo from URL
        parsed = urlparse(repo_url)
        path = parsed.path

        # Remove leading slash and trailing .git if present
        if path.startswith("/"):
            path = path[1:]
        if path.endswith(".git"):
            path = path[:-4]

        owner_repo = path

        # Authenticate with GitHub
        auth = Auth.Token(github_token)
        g = Github(auth=auth)

        # Get repository
        repo = g.get_repo(owner_repo)
        logger.info("repository_accessed", repo=owner_repo)

        # Create pull request
        pr = repo.create_pull(
            title=title, body=body, head=head_branch, base=base_branch, draft=draft
        )

        logger.info(
            "pull_request_created",
            pr_number=pr.number,
            url=pr.html_url,
            draft=draft,
        )
        return pr.number

    except GithubException as e:
        logger.error("pull_request_creation_failed", error=str(e), status=e.status)
        raise


def format_pr_body(
    approach: str,
    file_changes: list[dict],
    testing_notes: str,
    issue_number: int,
) -> str:
    """Format structured PR body.

    Args:
        approach: Summary of approach taken
        file_changes: List of dicts with keys: path, operation, explanation
        testing_notes: Testing instructions
        issue_number: GitHub issue number

    Returns:
        Formatted PR body markdown
    """
    # Build changes table
    table_rows = []
    for change in file_changes:
        path = change["path"]
        operation = change["operation"]
        explanation = change["explanation"]
        table_rows.append(f"| {path} | {operation} | {explanation} |")

    changes_table = "\n".join(table_rows)

    # Format body
    body = f"""## Summary
{approach}

## Changes
| File | Operation | Description |
|------|-----------|-------------|
{changes_table}

## Testing
{testing_notes}

---
Fixes #{issue_number}
Generated by [Booty](https://github.com/datashaman/booty)"""

    return body
